AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda para autenticação de documento e geração de JWT

Globals:
  Function:
    Timeout: 20
    MemorySize: 512

Resources:
  DocumentAuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: DocumentAuthFunction
      Handler: auth.document.DocumentAuthHandler::handleRequest
      Runtime: java21
      Architectures:
        - x86_64
      Environment:
        Variables:
          JWT_SECRET: "ZHVtbXktc2VjcmV0LWtleS1mb3Itand0LWhzMjU2LXN1cGVyLXNlY3VyZQ=="
          DB_HOST: "192.168.31.6"
          DB_PORT: "5433"
          DB_NAME: "challengeone"
          DB_USER: "postgres"
          DB_PASSWORD: "123"
      Events:
        Api:
          Type: Api
          Properties:
            Path: /auth
            Method: post

Outputs:
  DocumentAuthFunctionApi:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/auth/"
  DocumentAuthFunctionArn:
    Description: "Lambda ARN"
    Value: !GetAtt DocumentAuthFunction.Arn